/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jones.general;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import jones.actions.Action;
import jones.map.Grid;
import jones.map.Location;
import jones.map.MapManager;

/**
 *
 * @author dimid <dimidd@gmail.com>
 */
public class GUI extends javax.swing.JFrame implements ActionListener {

    private static final long serialVersionUID = 1L;
    private MapManager _map;
    private Game _game;
    private final Image _jonesImg;
    private int _lastSelectedBuildingActionIndex;

    /**
     * Creates new form GUI
     */
    public GUI(Game game) {
        _map = game.getMap();
        _game = game;
        ImageIcon img = new ImageIcon("./images/jones.png");
        _jonesImg = img.getImage().getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH);
        //initComponents();
        initComponents2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        scorePanel = new javax.swing.JPanel();
        scoreText = new javax.swing.JTextField();
        clothesLevelText = new javax.swing.JTextField();
        playerText = new javax.swing.JTextField();
        player = new javax.swing.JLabel();
        clothesLevel = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        possessionsLabel = new javax.swing.JLabel();
        possessionsText = new javax.swing.JTextField();
        jobLabel = new javax.swing.JLabel();
        jobText = new javax.swing.JTextField();
        experiencesLabel = new javax.swing.JLabel();
        experiencesText = new javax.swing.JTextField();
        buildingPanel = new javax.swing.JPanel();
        buildingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        announcementsPanel = new javax.swing.JPanel();
        announcementsLabel = new javax.swing.JLabel();
        endTurnButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        announcementsText = new javax.swing.JTextArea();
        aboutPanel = new javax.swing.JPanel();
        gameName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mapPanel.setLayout(new java.awt.GridLayout(4, 5));

        jButton1.setText("jButton1");
        mapPanel.add(jButton1);

        jButton2.setText("jButton1");
        mapPanel.add(jButton2);

        jButton3.setText("jButton1");
        mapPanel.add(jButton3);

        jButton4.setText("jButton1");
        mapPanel.add(jButton4);

        jButton5.setText("jButton1");
        mapPanel.add(jButton5);

        jButton6.setText("jButton1");
        mapPanel.add(jButton6);

        jButton10.setText("jButton1");
        mapPanel.add(jButton10);

        jButton12.setText("jButton1");
        mapPanel.add(jButton12);

        jButton9.setText("jButton1");
        mapPanel.add(jButton9);

        jButton8.setText("jButton1");
        mapPanel.add(jButton8);

        jButton11.setText("jButton1");
        mapPanel.add(jButton11);

        jButton7.setText("jButton1");
        mapPanel.add(jButton7);

        jButton13.setText("jButton1");
        mapPanel.add(jButton13);

        jButton14.setText("jButton1");
        mapPanel.add(jButton14);

        jButton15.setText("jButton1");
        mapPanel.add(jButton15);

        jButton16.setText("jButton1");
        mapPanel.add(jButton16);

        jButton17.setText("jButton1");
        mapPanel.add(jButton17);

        jButton18.setText("jButton1");
        mapPanel.add(jButton18);

        jButton19.setText("jButton1");
        mapPanel.add(jButton19);

        jButton20.setText("jButton1");
        mapPanel.add(jButton20);

        scoreText.setText("jTextField1");
        scoreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreTextActionPerformed(evt);
            }
        });

        clothesLevelText.setText("jTextField2");
        clothesLevelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothesLevelTextActionPerformed(evt);
            }
        });

        playerText.setText("jTextField3");

        player.setText("Player:");

        clothesLevel.setText("Clothes:");

        score.setText("Score:");

        possessionsLabel.setText("Possesions:");

        possessionsText.setText("jTextField1");

        jobLabel.setText("Job:");

        jobText.setText("jTextField1");

        experiencesLabel.setText("Experiences:");

        experiencesText.setText("jTextField1");

        javax.swing.GroupLayout scorePanelLayout = new javax.swing.GroupLayout(scorePanel);
        scorePanel.setLayout(scorePanelLayout);
        scorePanelLayout.setHorizontalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player)
                            .addComponent(possessionsLabel)
                            .addComponent(clothesLevel))
                        .addGap(21, 21, 21))
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jobLabel)
                            .addComponent(experiencesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addComponent(clothesLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(score)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(playerText, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(possessionsText)
                    .addComponent(jobText)
                    .addComponent(experiencesText))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        scorePanelLayout.setVerticalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clothesLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clothesLevel)
                    .addComponent(score))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player)
                    .addComponent(playerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(possessionsLabel)
                    .addComponent(possessionsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobLabel)
                    .addComponent(jobText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(experiencesLabel)
                    .addComponent(experiencesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buildingLabel.setText("Building Actions");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout buildingPanelLayout = new javax.swing.GroupLayout(buildingPanel);
        buildingPanel.setLayout(buildingPanelLayout);
        buildingPanelLayout.setHorizontalGroup(
            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buildingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(buildingLabel))
                .addGap(65, 65, 65))
        );
        buildingPanelLayout.setVerticalGroup(
            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingPanelLayout.createSequentialGroup()
                .addComponent(buildingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(0, 316, Short.MAX_VALUE))
        );

        announcementsLabel.setText("Announcements");

        endTurnButton.setText("End Turn");
        endTurnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endTurnButtonMouseClicked(evt);
            }
        });
        endTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTurnButtonActionPerformed(evt);
            }
        });

        announcementsText.setColumns(20);
        announcementsText.setRows(5);
        jScrollPane1.setViewportView(announcementsText);

        javax.swing.GroupLayout announcementsPanelLayout = new javax.swing.GroupLayout(announcementsPanel);
        announcementsPanel.setLayout(announcementsPanelLayout);
        announcementsPanelLayout.setHorizontalGroup(
            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, announcementsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, announcementsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(announcementsLabel)
                        .addGap(203, 203, 203)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(endTurnButton)
                .addGap(28, 28, 28))
        );
        announcementsPanelLayout.setVerticalGroup(
            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementsPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(endTurnButton)
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, announcementsPanelLayout.createSequentialGroup()
                .addComponent(announcementsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gameName.setText("Open Jones");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(announcementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(mapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)))
                .addComponent(buildingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(announcementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buildingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreTextActionPerformed

    private void clothesLevelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothesLevelTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clothesLevelTextActionPerformed

    private void endTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTurnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTurnButtonActionPerformed

    private void endTurnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endTurnButtonMouseClicked

        //remove player text from old position
        PlayerPosition curPos = _game.getCurPlayer().getPos();
        javax.swing.JButton butt = getButtons()[curPos.getY()][curPos.getX()];
        Location tile = (Location) _game.getMap().getGrid().get(curPos);
        butt.setText(tile.toString());

        _game.endTurn();
        repaint();
    }//GEN-LAST:event_endTurnButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        final MapManager map = MapManager.getDefaultMap();
        final Game g = new Game(map);
        Player p1 = new Player("Player1", null, map);
        g.addPlayer(p1);
        g.startGame();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //jButton21.set

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI(g).setVisible(true);
            }
        });
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);

 //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        buildingPanel.removeAll();
        javax.swing.GroupLayout buildingPanelLayout = new javax.swing.GroupLayout(buildingPanel);
        buildingPanel.setLayout(buildingPanelLayout);

        GroupLayout.ParallelGroup horizParallelGroup = buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        GroupLayout.ParallelGroup horizParallelGroup2 = buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        GroupLayout.SequentialGroup horizSequentialGroup = buildingPanelLayout.createSequentialGroup();

        buildingPanelLayout.setHorizontalGroup(horizParallelGroup);
        horizParallelGroup.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, horizSequentialGroup);



        horizSequentialGroup.addContainerGap(34, Short.MAX_VALUE);
        horizSequentialGroup.addGroup(horizParallelGroup2);
        
        horizParallelGroup2.addComponent(buildingLabel);
        horizSequentialGroup.addGap(65, 65, 65);





        GroupLayout.ParallelGroup vertParallelGroup = buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        GroupLayout.SequentialGroup vertSequentialGroup = buildingPanelLayout.createSequentialGroup();


        buildingPanelLayout.setVerticalGroup(vertParallelGroup);

        vertParallelGroup.addGroup(vertSequentialGroup);

        vertSequentialGroup.addComponent(buildingLabel);
 

        Graphics2D g2d = (Graphics2D) g;
        //g2d.drawImage(bg, 0, 0, null);
        PlayerPosition curPos = _game.getCurPlayer().getPos();
        javax.swing.JButton butt = _buttons[curPos.getY()][curPos.getX()];

        Location tile = (Location) _game.getMap().getGrid().get(curPos);
        butt.setText(convertToMultiline(tile.toString() + "\n\n" + curPos));
//        int x = (int) (0.5 * (butt.getX() + butt.getWidth()));
//        int y = (int) (0.5 * (butt.getY() + butt.getHeight()));
//        g2d.drawImage(_jonesImg, x, y, null);

        playerText.setText(_game.getCurPlayer().toString());
        scoreText.setText(_game.getCurPlayer().scoresString());
        clothesLevelText.setText(new Integer(_game.getCurPlayer().getClothesLevel()).toString());
        announcementsText.setText(_game.getAllAnnouncements());

        //_buildingActionLabels = null;
        
        //populate building panel
        if (curPos.isInBuilding()) {           
            ArrayList<? extends Action> possibletActions = _game.getPossibletActions();
            //_buildingActionLabels = new JLabel
            int actionID = 0;
            for (Action a : possibletActions) {
                javax.swing.JLabel label = new javax.swing.JLabel();
                if (null != a) {
                    label.setText(a.toString());
                    label.setForeground(Color.blue);
                    if (_lastSelectedBuildingActionIndex == actionID) {
                        label.setForeground(Color.YELLOW);
                    }
                    BuildingActionListener listener = new BuildingActionListener(_game, this, actionID, label, a);
                    label.addMouseListener(listener);
                } else {
                    label.setText("N\\A");
                    label.setForeground(Color.black);
                }

                horizParallelGroup2.addComponent(label);
                vertSequentialGroup.addComponent(label);
                vertSequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);

                ++actionID;
            }
                   
            vertSequentialGroup.addGap(0, 316, Short.MAX_VALUE);

        }
        else {
            _lastSelectedBuildingActionIndex = -1;
        }
        
        

        possessionsText.setText(_game.getCurPlayer().getPossessions().toString());
        jobText.setText(_game.getCurPlayer().getJob().toString());
        experiencesText.setText(_game.getCurPlayer().getExperiences().toString());
    }

    public int getLastSelectedBuildingActionIndex() {
        return _lastSelectedBuildingActionIndex;
    }

    public void setLastSelectedBuildingActionIndex(int _lastSelectedBuildingActionIndex) {
        this._lastSelectedBuildingActionIndex = _lastSelectedBuildingActionIndex;
    }

    @Override
    public void actionPerformed(ActionEvent e) {

        repaint();
    }
    private javax.swing.JButton[][] _buttons;

    public static String convertToMultiline(String orig) {

        return "<html>" + orig.replaceAll("\n", "<br>");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel announcementsLabel;
    private javax.swing.JPanel announcementsPanel;
    private javax.swing.JTextArea announcementsText;
    private javax.swing.JLabel buildingLabel;
    private javax.swing.JPanel buildingPanel;
    private javax.swing.JLabel clothesLevel;
    private javax.swing.JTextField clothesLevelText;
    private javax.swing.JButton endTurnButton;
    private javax.swing.JLabel experiencesLabel;
    private javax.swing.JTextField experiencesText;
    private javax.swing.JLabel gameName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jobLabel;
    private javax.swing.JTextField jobText;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JLabel player;
    private javax.swing.JTextField playerText;
    private javax.swing.JLabel possessionsLabel;
    private javax.swing.JTextField possessionsText;
    private javax.swing.JLabel score;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JTextField scoreText;
    // End of variables declaration//GEN-END:variables

    private void initComponents2() {
        //
        Grid grid = _map.getGrid();
        int width = grid.WIDTH;
        int height = grid.HEIGHT;
        Position pos = new Position(0, 0);


        _buttons = new JButton[height][width];
        Location tile;
        
        //initComponents();

        //mapPanel.removeAll();
        mapPanel = new javax.swing.JPanel();
        mapPanel.setLayout(new java.awt.GridLayout(height, width));
        for (int row = 0; row < height; ++row) {
            for (int col = 0; col < width; ++col) {
                _buttons[row][col] = new javax.swing.JButton();
                mapPanel.add(_buttons[row][col]);
                pos.setXY(col, row);
                tile = (Location) grid.get(pos);
                _buttons[row][col].setText(tile.toString());
                if (tile.isEnterable()) {
                    java.awt.event.MouseAdapter listener = new buildingListener(col, row, _game, this);
                    _buttons[row][col].addMouseListener(listener);
                }
                else {
                    _buttons[row][col].setEnabled(false);
                }
            }
        }


        //*******************************************************************************************************************
        //*******************************************            AUTO             *******************************************
        //******************************************************************************************************************* 
               scorePanel = new javax.swing.JPanel();
        scoreText = new javax.swing.JTextField();
        clothesLevelText = new javax.swing.JTextField();
        playerText = new javax.swing.JTextField();
        player = new javax.swing.JLabel();
        clothesLevel = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        possessionsLabel = new javax.swing.JLabel();
        possessionsText = new javax.swing.JTextField();
        jobLabel = new javax.swing.JLabel();
        jobText = new javax.swing.JTextField();
        experiencesLabel = new javax.swing.JLabel();
        experiencesText = new javax.swing.JTextField();
        buildingPanel = new javax.swing.JPanel();
        buildingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        announcementsPanel = new javax.swing.JPanel();
        announcementsLabel = new javax.swing.JLabel();
        endTurnButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        announcementsText = new javax.swing.JTextArea();
        aboutPanel = new javax.swing.JPanel();
        gameName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mapPanel.setLayout(new java.awt.GridLayout(4, 5));

//        jButton1.setText("jButton1");
//        mapPanel.add(jButton1);
//
//        jButton2.setText("jButton1");
//        mapPanel.add(jButton2);
//
//        jButton3.setText("jButton1");
//        mapPanel.add(jButton3);
//
//        jButton4.setText("jButton1");
//        mapPanel.add(jButton4);
//
//        jButton5.setText("jButton1");
//        mapPanel.add(jButton5);
//
//        jButton6.setText("jButton1");
//        mapPanel.add(jButton6);
//
//        jButton10.setText("jButton1");
//        mapPanel.add(jButton10);
//
//        jButton12.setText("jButton1");
//        mapPanel.add(jButton12);
//
//        jButton9.setText("jButton1");
//        mapPanel.add(jButton9);
//
//        jButton8.setText("jButton1");
//        mapPanel.add(jButton8);
//
//        jButton11.setText("jButton1");
//        mapPanel.add(jButton11);
//
//        jButton7.setText("jButton1");
//        mapPanel.add(jButton7);
//
//        jButton13.setText("jButton1");
//        mapPanel.add(jButton13);
//
//        jButton14.setText("jButton1");
//        mapPanel.add(jButton14);
//
//        jButton15.setText("jButton1");
//        mapPanel.add(jButton15);
//
//        jButton16.setText("jButton1");
//        mapPanel.add(jButton16);
//
//        jButton17.setText("jButton1");
//        mapPanel.add(jButton17);
//
//        jButton18.setText("jButton1");
//        mapPanel.add(jButton18);
//
//        jButton19.setText("jButton1");
//        mapPanel.add(jButton19);
//
//        jButton20.setText("jButton1");
//        mapPanel.add(jButton20);

        scoreText.setText("jTextField1");
        scoreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreTextActionPerformed(evt);
            }
        });

        clothesLevelText.setText("jTextField2");
        clothesLevelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothesLevelTextActionPerformed(evt);
            }
        });

        playerText.setText("jTextField3");

        player.setText("Player:");

        clothesLevel.setText("Clothes:");

        score.setText("Score:");

        possessionsLabel.setText("Possesions:");

        possessionsText.setText("jTextField1");

        jobLabel.setText("Job:");

        jobText.setText("jTextField1");

        experiencesLabel.setText("Experiences:");

        experiencesText.setText("jTextField1");

        javax.swing.GroupLayout scorePanelLayout = new javax.swing.GroupLayout(scorePanel);
        scorePanel.setLayout(scorePanelLayout);
        scorePanelLayout.setHorizontalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player)
                            .addComponent(possessionsLabel)
                            .addComponent(clothesLevel))
                        .addGap(21, 21, 21))
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jobLabel)
                            .addComponent(experiencesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addComponent(clothesLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(score)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(playerText, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(possessionsText)
                    .addComponent(jobText)
                    .addComponent(experiencesText))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        scorePanelLayout.setVerticalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clothesLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clothesLevel)
                    .addComponent(score))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player)
                    .addComponent(playerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(possessionsLabel)
                    .addComponent(possessionsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobLabel)
                    .addComponent(jobText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(experiencesLabel)
                    .addComponent(experiencesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buildingLabel.setText("Building Actions");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout buildingPanelLayout = new javax.swing.GroupLayout(buildingPanel);
        buildingPanel.setLayout(buildingPanelLayout);
        buildingPanelLayout.setHorizontalGroup(
            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buildingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(buildingLabel))
                .addGap(65, 65, 65))
        );
        buildingPanelLayout.setVerticalGroup(
            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingPanelLayout.createSequentialGroup()
                .addComponent(buildingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(0, 316, Short.MAX_VALUE))
        );

        announcementsLabel.setText("Announcements");

        endTurnButton.setText("End Turn");
        endTurnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endTurnButtonMouseClicked(evt);
            }
        });
        endTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTurnButtonActionPerformed(evt);
            }
        });

        announcementsText.setColumns(20);
        announcementsText.setRows(5);
        jScrollPane1.setViewportView(announcementsText);

        javax.swing.GroupLayout announcementsPanelLayout = new javax.swing.GroupLayout(announcementsPanel);
        announcementsPanel.setLayout(announcementsPanelLayout);
        announcementsPanelLayout.setHorizontalGroup(
            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, announcementsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, announcementsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(announcementsLabel)
                        .addGap(203, 203, 203)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(endTurnButton)
                .addGap(28, 28, 28))
        );
        announcementsPanelLayout.setVerticalGroup(
            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementsPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(endTurnButton)
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, announcementsPanelLayout.createSequentialGroup()
                .addComponent(announcementsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gameName.setText("Open Jones");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(announcementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(mapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)))
                .addComponent(buildingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(announcementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buildingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();

        
        
        
        
        
        
        
        
        

//
//        scorePanel = new javax.swing.JPanel();
//        scoreText = new javax.swing.JTextField();
//        clothesLevelText = new javax.swing.JTextField();
//        playerText = new javax.swing.JTextField();
//        player = new javax.swing.JLabel();
//        clothesLevel = new javax.swing.JLabel();
//        score = new javax.swing.JLabel();
//        possessionsLabel = new javax.swing.JLabel();
//        possessionsText = new javax.swing.JTextField();
//        buildingPanel = new javax.swing.JPanel();
//        buildingLabel = new javax.swing.JLabel();
//        announcementsPanel = new javax.swing.JPanel();
//        announcementsLabel = new javax.swing.JLabel();
//        endTurnButton = new javax.swing.JButton();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        announcementsText = new javax.swing.JTextArea();
//        aboutPanel = new javax.swing.JPanel();
//        gameName = new javax.swing.JLabel();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        scoreText.setText("jTextField1");
//        scoreText.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                scoreTextActionPerformed(evt);
//            }
//        });
//
//        clothesLevelText.setText("jTextField2");
//        clothesLevelText.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                clothesLevelTextActionPerformed(evt);
//            }
//        });
//
//        playerText.setText("jTextField3");
//
//        player.setText("Player:");
//
//        clothesLevel.setText("Clothes:");
//
//        score.setText("Score:");
//
//        possessionsLabel.setText("Possesions:");
//
//        possessionsText.setText("jTextField1");
//
//        
//        
//        /////////////////////////////////////////////////////////////////////////////
//           javax.swing.GroupLayout scorePanelLayout = new javax.swing.GroupLayout(scorePanel);
//        scorePanel.setLayout(scorePanelLayout);
//        scorePanelLayout.setHorizontalGroup(
//            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scorePanelLayout.createSequentialGroup()
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(player)
//                    .addComponent(possessionsLabel)
//                    .addComponent(clothesLevel))
//                .addGap(21, 21, 21)
//                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                    .addGroup(scorePanelLayout.createSequentialGroup()
//                        .addComponent(clothesLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(score)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addComponent(playerText, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
//                    .addComponent(possessionsText))
//                .addGap(273, 273, 273))
//        );
//        scorePanelLayout.setVerticalGroup(
//            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(scorePanelLayout.createSequentialGroup()
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(clothesLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(clothesLevel)
//                    .addComponent(score))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(player)
//                    .addComponent(playerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(possessionsLabel)
//                    .addComponent(possessionsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addContainerGap())
//        );
//
//        buildingLabel.setText("Building Actions");
//       
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//
//        jLabel1.setText("jLabel1");
//
//        jLabel2.setText("jLabel2");
//
//        jLabel3.setText("jLabel3");
//
//        jLabel4.setText("jLabel4");
//
//        javax.swing.GroupLayout buildingPanelLayout = new javax.swing.GroupLayout(buildingPanel);
//        buildingPanel.setLayout(buildingPanelLayout);
//        buildingPanelLayout.setHorizontalGroup(
//            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buildingPanelLayout.createSequentialGroup()
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addGroup(buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jLabel4)
//                    .addComponent(jLabel3)
//                    .addComponent(jLabel1)
//                    .addComponent(jLabel2)
//                    .addComponent(buildingLabel))
//                .addGap(65, 65, 65))
//        );
//        buildingPanelLayout.setVerticalGroup(
//            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(buildingPanelLayout.createSequentialGroup()
//                .addComponent(buildingLabel)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jLabel1)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jLabel2)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jLabel3)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jLabel4)
//                .addGap(0, 316, Short.MAX_VALUE))
//        );
//        announcementsLabel.setText("Announcements");
//
//        endTurnButton.setText("End Turn");
//        endTurnButton.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                endTurnButtonMouseClicked(evt);
//            }
//        });
//        endTurnButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                endTurnButtonActionPerformed(evt);
//            }
//        });
//
//        announcementsText.setColumns(20);
//        announcementsText.setRows(5);
//        jScrollPane1.setViewportView(announcementsText);
//
//        javax.swing.GroupLayout announcementsPanelLayout = new javax.swing.GroupLayout(announcementsPanel);
//        announcementsPanel.setLayout(announcementsPanelLayout);
//        announcementsPanelLayout.setHorizontalGroup(
//            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, announcementsPanelLayout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, announcementsPanelLayout.createSequentialGroup()
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addComponent(announcementsLabel)
//                        .addGap(203, 203, 203)))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(endTurnButton)
//                .addGap(28, 28, 28))
//        );
//        announcementsPanelLayout.setVerticalGroup(
//            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(announcementsPanelLayout.createSequentialGroup()
//                .addGap(48, 48, 48)
//                .addComponent(endTurnButton)
//                .addGap(0, 49, Short.MAX_VALUE))
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, announcementsPanelLayout.createSequentialGroup()
//                .addComponent(announcementsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())
//        );
//
//        gameName.setText("Open Jones");
//
//        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
//        aboutPanel.setLayout(aboutPanelLayout);
//        aboutPanelLayout.setHorizontalGroup(
//            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 130, Short.MAX_VALUE)
//            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(aboutPanelLayout.createSequentialGroup()
//                    .addContainerGap()
//                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//        );
//        aboutPanelLayout.setVerticalGroup(
//            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 100, Short.MAX_VALUE)
//            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(aboutPanelLayout.createSequentialGroup()
//                    .addGap(16, 16, 16)
//                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addContainerGap(17, Short.MAX_VALUE)))
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(announcementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addGap(78, 78, 78))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(27, 27, 27)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(scorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(mapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(buildingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(announcementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(scorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(buildingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(0, 0, Short.MAX_VALUE))))
//        );
//
//        pack();

  
    }

    javax.swing.JButton[][] getButtons() {
        return _buttons;
    }
}
