/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jones.general;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import jones.actions.Action;
import jones.map.Grid;
import jones.map.Location;
import jones.map.MapManager;

/**
 *
 * @author dimid <dimidd@gmail.com>
 */
public class GUI extends javax.swing.JFrame implements ActionListener {

    private static final long serialVersionUID = 1L;
    protected MapManager _map;
    protected Game _game;
    protected final Image _jonesImg;
    protected int _lastSelectedBuildingActionIndex;
    private ArrayList<Action> _possibletActions;
    private GUIGraphics _guiGraphics;
    private MyGlassPane _glassPane;
    private static final int TILE_WIDTH = 155;
    private static final int TILE_HIGHT = 96;

    /**
     * Creates new form GUI
     */
    public GUI(Game game) {
        _map = game.getMap();
        _game = game;
        ImageIcon img = new ImageIcon("./images/jones.png");
        _jonesImg = img.getImage().getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH);
        _possibletActions = null;
        initComponents2();
        //initComponents2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        scorePanel = new javax.swing.JPanel();
        scoreText = new javax.swing.JTextField();
        clothesLevelText = new javax.swing.JTextField();
        playerText = new javax.swing.JTextField();
        player = new javax.swing.JLabel();
        clothesLevel = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        possessionsLabel = new javax.swing.JLabel();
        possessionsText = new javax.swing.JTextField();
        jobLabel = new javax.swing.JLabel();
        jobText = new javax.swing.JTextField();
        experiencesLabel = new javax.swing.JLabel();
        experiencesText = new javax.swing.JTextField();
        buildingPanel = new javax.swing.JPanel();
        buildingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        announcementsPanel = new javax.swing.JPanel();
        announcementsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        announcementsText = new javax.swing.JTextArea();
        aboutPanel = new javax.swing.JPanel();
        gameName = new javax.swing.JLabel();
        endTurnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mapPanel.setLayout(new java.awt.GridLayout(5, 5));

        jButton1.setText("jButton1");
        mapPanel.add(jButton1);

        jButton2.setText("jButton1");
        mapPanel.add(jButton2);

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        mapPanel.add(jButton3);

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        mapPanel.add(jButton4);

        jButton5.setText("jButton1");
        mapPanel.add(jButton5);

        jButton6.setText("jButton1");
        mapPanel.add(jButton6);

        jButton10.setText("jButton1");
        mapPanel.add(jButton10);

        jButton12.setText("jButton1");
        mapPanel.add(jButton12);

        jButton9.setText("jButton1");
        mapPanel.add(jButton9);

        jButton8.setText("jButton1");
        mapPanel.add(jButton8);

        jButton11.setText("jButton1");
        mapPanel.add(jButton11);

        jButton7.setText("jButton1");
        mapPanel.add(jButton7);

        jButton13.setText("jButton1");
        mapPanel.add(jButton13);

        jButton14.setText("jButton1");
        mapPanel.add(jButton14);

        jButton15.setText("jButton1");
        mapPanel.add(jButton15);

        jButton16.setText("jButton1");
        mapPanel.add(jButton16);

        jButton17.setText("jButton1");
        mapPanel.add(jButton17);

        jButton18.setText("jButton1");
        mapPanel.add(jButton18);

        jButton19.setText("jButton1");
        mapPanel.add(jButton19);

        jButton20.setText("jButton1");
        mapPanel.add(jButton20);

        scoreText.setText("jTextField1");
        scoreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreTextActionPerformed(evt);
            }
        });

        clothesLevelText.setText("jTextField2");
        clothesLevelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothesLevelTextActionPerformed(evt);
            }
        });

        playerText.setText("jTextField3");

        player.setText("Player:");

        clothesLevel.setText("Clothes:");

        score.setText("Score:");

        possessionsLabel.setText("Possesions:");

        possessionsText.setText("jTextField1");

        jobLabel.setText("Job:");

        jobText.setText("jTextField1");

        experiencesLabel.setText("Experiences:");

        experiencesText.setText("jTextField1");

        javax.swing.GroupLayout scorePanelLayout = new javax.swing.GroupLayout(scorePanel);
        scorePanel.setLayout(scorePanelLayout);
        scorePanelLayout.setHorizontalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clothesLevel)
                            .addComponent(player))
                        .addGap(18, 18, 18)
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(scorePanelLayout.createSequentialGroup()
                                .addComponent(clothesLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(score)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scoreText))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scorePanelLayout.createSequentialGroup()
                                .addGap(0, 26, Short.MAX_VALUE)
                                .addComponent(playerText, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scorePanelLayout.createSequentialGroup()
                                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(possessionsLabel)
                                    .addComponent(jobLabel))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scorePanelLayout.createSequentialGroup()
                                .addComponent(experiencesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jobText, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                            .addComponent(experiencesText)
                            .addComponent(possessionsText))))
                .addContainerGap())
        );
        scorePanelLayout.setVerticalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(score))
                    .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clothesLevel)
                        .addComponent(clothesLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player)
                    .addComponent(playerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(possessionsLabel)
                    .addComponent(possessionsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jobText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(experiencesLabel)
                    .addComponent(experiencesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buildingLabel.setText("Building Actions");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout buildingPanelLayout = new javax.swing.GroupLayout(buildingPanel);
        buildingPanel.setLayout(buildingPanelLayout);
        buildingPanelLayout.setHorizontalGroup(
            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(buildingLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buildingPanelLayout.setVerticalGroup(
            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingPanelLayout.createSequentialGroup()
                .addComponent(buildingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(0, 215, Short.MAX_VALUE))
        );

        announcementsLabel.setText("Announcements");

        announcementsText.setColumns(20);
        announcementsText.setRows(5);
        jScrollPane1.setViewportView(announcementsText);

        javax.swing.GroupLayout announcementsPanelLayout = new javax.swing.GroupLayout(announcementsPanel);
        announcementsPanel.setLayout(announcementsPanelLayout);
        announcementsPanelLayout.setHorizontalGroup(
            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementsPanelLayout.createSequentialGroup()
                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(announcementsPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(announcementsLabel))
                    .addGroup(announcementsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        announcementsPanelLayout.setVerticalGroup(
            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, announcementsPanelLayout.createSequentialGroup()
                .addComponent(announcementsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gameName.setText("Open Jones");

        endTurnButton.setText("End Turn");
        endTurnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endTurnButtonMouseClicked(evt);
            }
        });
        endTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTurnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(endTurnButton)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelLayout.createSequentialGroup()
                .addGap(0, 73, Short.MAX_VALUE)
                .addComponent(endTurnButton))
            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buildingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(scorePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(announcementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(announcementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreTextActionPerformed

    private void clothesLevelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothesLevelTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clothesLevelTextActionPerformed

    private void endTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTurnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTurnButtonActionPerformed

    private void endTurnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endTurnButtonMouseClicked

        //remove player text from old position
        PlayerPosition curPos = _game.getCurPlayer().getPos();
        javax.swing.JButton butt = getButtons()[curPos.getY()][curPos.getX()];
        Location tile = (Location) _game.getMap().getGrid().get(curPos);
        butt.setText(tile.toString());

        _game.endTurn();
        repaint();
    }//GEN-LAST:event_endTurnButtonMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        final MapManager map = MapManager.getDefaultMap();
        final Game g = new Game(map);
        Player p1 = new Player("Player1", null, map);
        g.addPlayer(p1);
        g.startGame();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //jButton21.set

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                GUI gui = new GUI(g);
                gui.setLocationRelativeTo(null);
                gui.setVisible(true);
            }
        });
    }

    @Override
    public void paint(Graphics g) {
        PlayerPosition pos = _game.getCurPlayer().getPos();
        int x = _buttons[pos.getY()][pos.getX()].getX();
        int y = _buttons[pos.getY()][pos.getX()].getY();
      
        _glassPane.setPoint(new Point ( x + TILE_WIDTH/2,  y + (int) (2.5*TILE_HIGHT) ));
        this.setGlassPane(_glassPane);
        _glassPane.setVisible(true);
        _glassPane.repaint();
        super.paint(g);

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        buildingPanel.removeAll();
        javax.swing.GroupLayout buildingPanelLayout = new javax.swing.GroupLayout(buildingPanel);
        buildingPanel.setLayout(buildingPanelLayout);

        GroupLayout.ParallelGroup horizParallelGroup = buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        GroupLayout.ParallelGroup horizParallelGroup2 = buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        GroupLayout.SequentialGroup horizSequentialGroup = buildingPanelLayout.createSequentialGroup();

        buildingPanelLayout.setHorizontalGroup(horizParallelGroup);
        horizParallelGroup.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, horizSequentialGroup);



        horizSequentialGroup.addContainerGap(34, Short.MAX_VALUE);
        horizSequentialGroup.addGroup(horizParallelGroup2);

        horizParallelGroup2.addComponent(buildingLabel);
        horizSequentialGroup.addGap(65, 65, 65);





        GroupLayout.ParallelGroup vertParallelGroup = buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        GroupLayout.SequentialGroup vertSequentialGroup = buildingPanelLayout.createSequentialGroup();


        buildingPanelLayout.setVerticalGroup(vertParallelGroup);

        vertParallelGroup.addGroup(vertSequentialGroup);

        vertSequentialGroup.addComponent(buildingLabel);


        Graphics2D g2d = (Graphics2D) g;
        //g2d.drawImage(bg, 0, 0, null);
        PlayerPosition curPos = _game.getCurPlayer().getPos();
        javax.swing.JButton butt = _buttons[curPos.getY()][curPos.getX()];

        Location tile = (Location) _game.getMap().getGrid().get(curPos);
        //butt.setText(convertToMultiline(tile.toString() + "\n\n" + curPos));
//        int x = (int) (0.5 * (butt.getX() + butt.getWidth()));
//        int y = (int) (0.5 * (butt.getY() + butt.getHeight()));
//        g2d.drawImage(_jonesImg, x, y, null);

        playerText.setText(_game.getCurPlayer().toString());
        scoreText.setText(_game.getCurPlayer().scoresString());
        clothesLevelText.setText(new Integer(_game.getCurPlayer().getClothesLevel()).toString());
        announcementsText.setText(_game.getAllAnnouncements());

        //_buildingActionLabels = null;

        //populate building panel
        if (curPos.isInBuilding()) {
            _possibletActions = _game.getPossibletActions();
            //_buildingActionLabels = new JLabel
            int actionID = 0;
            for (Action a : _possibletActions) {
                javax.swing.JLabel label = new javax.swing.JLabel();
                if (null != a) {
                    label.setText(a.toString());
                    label.setForeground(Color.blue);
                    if (_lastSelectedBuildingActionIndex == actionID) {
                        label.setForeground(Color.YELLOW);
                    }
                    BuildingActionListener listener = new BuildingActionListener(_game, this, actionID, label, a);
                    label.addMouseListener(listener);
                } else {
                    label.setText("N\\A");
                    label.setForeground(Color.black);
                }

                horizParallelGroup2.addComponent(label);
                vertSequentialGroup.addComponent(label);
                vertSequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);

                ++actionID;
            }

            vertSequentialGroup.addGap(0, 316, Short.MAX_VALUE);

        } else {
            _lastSelectedBuildingActionIndex = -1;
        }



        possessionsText.setText(_game.getCurPlayer().getPossessions().toString());
        jobText.setText(_game.getCurPlayer().getJob().toString());
        experiencesText.setText(_game.getCurPlayer().getExperiences().toString());
    }

    public ArrayList<Action> getPossibletActions() {
        return _possibletActions;
    }

    public int getLastSelectedBuildingActionIndex() {
        return _lastSelectedBuildingActionIndex;
    }

    public void setLastSelectedBuildingActionIndex(int _lastSelectedBuildingActionIndex) {
        this._lastSelectedBuildingActionIndex = _lastSelectedBuildingActionIndex;
    }

    @Override
    public void actionPerformed(ActionEvent e) {

        repaint();
    }
    private javax.swing.JButton[][] _buttons;

    public static String convertToMultiline(String orig) {

        return "<html>" + orig.replaceAll("\n", "<br>");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel announcementsLabel;
    private javax.swing.JPanel announcementsPanel;
    private javax.swing.JTextArea announcementsText;
    private javax.swing.JLabel buildingLabel;
    private javax.swing.JPanel buildingPanel;
    private javax.swing.JLabel clothesLevel;
    private javax.swing.JTextField clothesLevelText;
    private javax.swing.JButton endTurnButton;
    private javax.swing.JLabel experiencesLabel;
    private javax.swing.JTextField experiencesText;
    private javax.swing.JLabel gameName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jobLabel;
    private javax.swing.JTextField jobText;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JLabel player;
    private javax.swing.JTextField playerText;
    private javax.swing.JLabel possessionsLabel;
    private javax.swing.JTextField possessionsText;
    private javax.swing.JLabel score;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JTextField scoreText;
    // End of variables declaration//GEN-END:variables

    private void initComponents2() {
        //
        Grid grid = _map.getGrid();
        int width = grid.WIDTH;
        int height = grid.HEIGHT;
        Position pos = new Position(0, 0);
        _guiGraphics = new GUIGraphics();

        _buttons = new JButton[height][width];
        Location tile;
        _glassPane = new MyGlassPane(this);
        this.setGlassPane(_glassPane);
        
        //initComponents();

        //mapPanel.removeAll();
        mapPanel = new javax.swing.JPanel();
        GridLayout gridLayout = new java.awt.GridLayout(height, width);
        gridLayout.setHgap(0);
        gridLayout.setVgap(0);
        mapPanel.setLayout(gridLayout);
        mapPanel.setAlignmentX(0);
        mapPanel.setAlignmentY(0);
        //mapPanel.set
        
       // mapPanel.setSize(new Dimension( width * 155, height * 96));
        for (int row = 0; row < height; ++row) {
            for (int col = 0; col < width; ++col) {
                _buttons[row][col] = new javax.swing.JButton();
                //_buttons[row][col].setBorder(BorderFactory.createEmptyBorder());
                 //_buttons[row][col].setContentAreaFilled(false);
                 _buttons[row][col].setBorder(null);
                 _buttons[row][col].setBorderPainted(false);
                 _buttons[row][col].setOpaque(true);
                 _buttons[row][col].setMargin(new Insets(0, 0, 0, 0));
                // _buttons[row][col].setSize(new Dimension(  155,  96));
                mapPanel.add(_buttons[row][col]);
                
                pos.setXY(col, row);
                tile = (Location) grid.get(pos);
                // _buttons[row][col].setText(tile.toString());
                Icon tileIcon = null;
                try {
                    String name = tile.getName();
                    tileIcon = _guiGraphics.getTileIcon(name);
                    if (null != tileIcon) {
                        _buttons[row][col].setIcon(tileIcon);
                    }
                    //_buttons[row][col].setIcon(new SVGIcon("/home/dimid/NetBeansProjects/openjones/openjones/images/Gerald_G_Small_House.svg",_buttons[row][col].getWidth() , _buttons[row][col].getHeight()));
                } catch (Exception ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                if (tile.isEnterable()) {
                    java.awt.event.MouseAdapter listener = new BuildingListener(col, row, _game, this);
                    _buttons[row][col].addMouseListener(listener);
                } else {
                    if (null == tileIcon)
                        _buttons[row][col].setEnabled(false);
                }
            }
        }


        //*******************************************************************************************************************
        //*******************************************            AUTO             *******************************************
        //******************************************************************************************************************* 


        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        scorePanel = new javax.swing.JPanel();
        scoreText = new javax.swing.JTextField();
        clothesLevelText = new javax.swing.JTextField();
        playerText = new javax.swing.JTextField();
        player = new javax.swing.JLabel();
        clothesLevel = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        possessionsLabel = new javax.swing.JLabel();
        possessionsText = new javax.swing.JTextField();
        jobLabel = new javax.swing.JLabel();
        jobText = new javax.swing.JTextField();
        experiencesLabel = new javax.swing.JLabel();
        experiencesText = new javax.swing.JTextField();
        buildingPanel = new javax.swing.JPanel();
        buildingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        announcementsPanel = new javax.swing.JPanel();
        announcementsLabel = new javax.swing.JLabel();
        endTurnButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        announcementsText = new javax.swing.JTextArea();
        aboutPanel = new javax.swing.JPanel();
        gameName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //mapPanel.setLayout(new java.awt.GridLayout(5, 5));

//        jButton1.setText("jButton1");
//        mapPanel.add(jButton1);
//
//        jButton2.setText("jButton1");
//        mapPanel.add(jButton2);
//
//        jButton3.setText("jButton1");
//        jButton3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton3ActionPerformed(evt);
//            }
//        });
//        mapPanel.add(jButton3);
//
//        jButton4.setText("jButton1");
//        jButton4.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton4ActionPerformed(evt);
//            }
//        });
//        mapPanel.add(jButton4);
//
//        jButton5.setText("jButton1");
//        mapPanel.add(jButton5);
//
//        jButton6.setText("jButton1");
//        mapPanel.add(jButton6);
//
//        jButton10.setText("jButton1");
//        mapPanel.add(jButton10);
//
//        jButton12.setText("jButton1");
//        mapPanel.add(jButton12);
//
//        jButton9.setText("jButton1");
//        mapPanel.add(jButton9);
//
//        jButton8.setText("jButton1");
//        mapPanel.add(jButton8);
//
//        jButton11.setText("jButton1");
//        mapPanel.add(jButton11);
//
//        jButton7.setText("jButton1");
//        mapPanel.add(jButton7);
//
//        jButton13.setText("jButton1");
//        mapPanel.add(jButton13);
//
//        jButton14.setText("jButton1");
//        mapPanel.add(jButton14);
//
//        jButton15.setText("jButton1");
//        mapPanel.add(jButton15);
//
//        jButton16.setText("jButton1");
//        mapPanel.add(jButton16);
//
//        jButton17.setText("jButton1");
//        mapPanel.add(jButton17);
//
//        jButton18.setText("jButton1");
//        mapPanel.add(jButton18);
//
//        jButton19.setText("jButton1");
//        mapPanel.add(jButton19);
//
//        jButton20.setText("jButton1");
//        mapPanel.add(jButton20);
//
//        scoreText.setText("jTextField1");
//        scoreText.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                scoreTextActionPerformed(evt);
//            }
//        });
//
//        clothesLevelText.setText("jTextField2");
//        clothesLevelText.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                clothesLevelTextActionPerformed(evt);
//            }
//        });
//
//        playerText.setText("jTextField3");

        player.setText("Player:");

        clothesLevel.setText("Clothes:");

        score.setText("Score:");

        possessionsLabel.setText("Possesions:");

        possessionsText.setText("jTextField1");

        jobLabel.setText("Job:");

        jobText.setText("jTextField1");

        experiencesLabel.setText("Experiences:");
        
        
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
               javax.swing.GroupLayout scorePanelLayout = new javax.swing.GroupLayout(scorePanel);
        scorePanel.setLayout(scorePanelLayout);
        scorePanelLayout.setHorizontalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clothesLevel)
                            .addComponent(player))
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(scorePanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(clothesLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(score)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scorePanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(playerText, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scorePanelLayout.createSequentialGroup()
                                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(possessionsLabel)
                                    .addComponent(jobLabel))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scorePanelLayout.createSequentialGroup()
                                .addComponent(experiencesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jobText)
                            .addComponent(possessionsText, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                            .addComponent(experiencesText))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        scorePanelLayout.setVerticalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clothesLevel)
                    .addComponent(clothesLevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(score)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player)
                    .addComponent(playerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(possessionsLabel)
                    .addComponent(possessionsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jobText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(experiencesLabel)
                    .addComponent(experiencesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buildingLabel.setText("Building Actions");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout buildingPanelLayout = new javax.swing.GroupLayout(buildingPanel);
        buildingPanel.setLayout(buildingPanelLayout);
        buildingPanelLayout.setHorizontalGroup(
            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(buildingLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buildingPanelLayout.setVerticalGroup(
            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingPanelLayout.createSequentialGroup()
                .addComponent(buildingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(0, 316, Short.MAX_VALUE))
        );

        announcementsLabel.setText("Announcements");

        announcementsText.setColumns(20);
        announcementsText.setRows(5);
        jScrollPane1.setViewportView(announcementsText);

        javax.swing.GroupLayout announcementsPanelLayout = new javax.swing.GroupLayout(announcementsPanel);
        announcementsPanel.setLayout(announcementsPanelLayout);
        announcementsPanelLayout.setHorizontalGroup(
            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementsPanelLayout.createSequentialGroup()
                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(announcementsPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(announcementsLabel))
                    .addGroup(announcementsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        announcementsPanelLayout.setVerticalGroup(
            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, announcementsPanelLayout.createSequentialGroup()
                .addComponent(announcementsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gameName.setText("Open Jones");

        endTurnButton.setText("End Turn");
        endTurnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endTurnButtonMouseClicked(evt);
            }
        });
        endTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTurnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(endTurnButton)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelLayout.createSequentialGroup()
                .addGap(0, 73, Short.MAX_VALUE)
                .addComponent(endTurnButton))
            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buildingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(scorePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(announcementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(announcementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buildingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();

        
        
        

    }

    public MyGlassPane getGlassPane() {
        return _glassPane;
    }

    javax.swing.JButton[][] getButtons() {
        return _buttons;
    }
}
